project:
  type: book
  output-dir: _site
  resources:
    - "/.nojekyll"

book:
  title: "Test site"
  subtitle: "Setup using quarto"
  author: "Tylar Murray"
  repo-url: https://github.com/7yl4r/quarto-test
  reader-mode: true
  repo-actions: [edit]
  search: true
  date: today
  date-format: "YYYY-MM-DD"
  page-navigation: true
  page-footer:
    left: |
      Website created by instructors, with attribution to external content
    right: |
      This book was built with <a href="https://quarto.org/" target="_blank">Quarto</a>
  chapters:
    - index.qmd
#     - part: "Modules"
#       chapters:
#         - intro.qmd
#         - quarto.qmd
#         - shiny.qmd
#         - ui_design.qmd
#     - part: resources.qmd
#       chapters:
#         - resources/useful.qmd
#         - resources/tbepwq.qmd
#   appendices:
#     - setup.qmd
#     - rintro.qmd
#     - addlquarto.qmd
#     - references.qmd

# bibliography: references.bib

format:
  html:
    theme:
      - cosmo
    css: libs/style.css
    code-tools:
      source: repo
    code-link: true
    toc-depth: 4
  # pdf:
  #   documentclass: scrreprt
  #   prefer-html: true
